CREATE TABLE dbo.Notifications (
    NotificationId INT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NOT NULL REFERENCES dbo.Users(UserId) ON DELETE CASCADE,
    Title NVARCHAR(100) NOT NULL,
    Message NVARCHAR(500) NOT NULL,
    IsRead BIT NOT NULL,
    EmailSentAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME())
);
