CREATE TABLE dbo.AuditLogs (
    AuditLogId BIGINT IDENTITY(1,1) PRIMARY KEY,
    UserId INT NULL REFERENCES dbo.Users(UserId) ON DELETE SET NULL,
    Action NVARCHAR(100) NOT NULL,
    EntityName NVARCHAR(50) NOT NULL,
    EntityId INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT (SYSUTCDATETIME())
);
