using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Aarogyam.API.Services;

public class PdfService : IPdfService
{
    public byte[] GeneratePrescriptionPdf(
        string patientName,
        string doctorName,
        string diagnosisTitle,
        DateTime prescriptionDate,
        string prescriptionText)
    {
        var document = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(style => style.FontSize(11));

                page.Header().Column(column =>
                {
                    column.Item().Text("Aarogyam").FontSize(20).Bold();
                    column.Item().Text("Digital Health Identity — Prescription").FontSize(10).FontColor(Colors.Grey.Darken1);
                    column.Item().PaddingTop(8).LineHorizontal(1).LineColor(Colors.Grey.Lighten1);
                });

                page.Content().PaddingTop(16).Column(column =>
                {
                    column.Spacing(6);

                    column.Item().Text($"Patient: {patientName}").Bold();
                    column.Item().Text($"Doctor: {doctorName}");
                    column.Item().Text($"Diagnosis: {diagnosisTitle}");
                    column.Item().Text($"Date: {prescriptionDate:dd MMM yyyy}");

                    column.Item().PaddingTop(12).LineHorizontal(1).LineColor(Colors.Grey.Lighten2);

                    column.Item().PaddingTop(12).Text("Prescription").Bold().FontSize(13);
                    column.Item().Text(prescriptionText).LineHeight(1.4f);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by Aarogyam — ").FontColor(Colors.Grey.Darken1).FontSize(9);
                    text.Span(DateTime.UtcNow.ToString("dd MMM yyyy HH:mm") + " UTC").FontColor(Colors.Grey.Darken1).FontSize(9);
                });
            });
        });

        return document.GeneratePdf();
    }
}
